apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.urls import reverse_lazy

from pages.views import PageDetailView

from .forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from .views import UserCreateView, UserDetailView, UserUpdateView

app_name = 'accounts'
urlpatterns = [
    url(r'^registration/$', UserCreateView.as_view(), name='registration'),
    url(
        r'^login/$',
        views.LoginView.as_view(
            template_name='accounts/login.html',
            form_class=LoginForm,
        ),
        name='login'
    ),
    url(
        r'^logout/$',
        views.LogoutView.as_view(
            template_name='accounts/logout.html',
        ),
        name='logout'
    ),
    url(
        r'^password-reset/$',
        views.PasswordResetView.as_view(
            email_template_name='accounts/emails/password_reset_email.html',
            form_class=PasswordResetForm,
            success_url=reverse_lazy('accounts:password-reset-done'),
            template_name='accounts/password_reset_form.html',
        ),
        name='password-reset',
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(
            form_class=SetPasswordForm,
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password-reset-complete'),
        ),
        name='password-reset-confirm'
    ),
    url(
        r'^password-reset/done/$',
        views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password-reset-done'
    ),
    url(
        r'^reset/done/$',
        views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password-reset-complete',
    ),
    url(r'^profile/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^update/$', UserUpdateView.as_view(), name='user-update'),
    url(
        r'^password-change/$',
        views.PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            form_class=PasswordChangeForm,
            success_url=reverse_lazy('accounts:user-detail')
        ),
        name='password-change',
    ),
    url(r'^thank-you/$', PageDetailView.as_view(), name='registration-thank-you'),
]

apps/directory/urls.py
from django.conf.urls import url

from .views import OrganisationDetailView, OrganisationListView, OrganisationUserView

app_name = 'directory'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', OrganisationDetailView.as_view(), name='organisation-detail'),
    url(r'^$', OrganisationListView.as_view(), name='organisation-list'),
    url(r'^people/(?P<pk>\d+)/$', OrganisationUserView.as_view(), name='organisation-user'),
]

commonslibrary/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve as staticfiles_serve
from django.http import HttpResponseServerError
from django.template import TemplateDoesNotExist, loader
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.views.static import serve

from core.views import HomeView, SearchView
from resources.views import ResourceCategoryListView

admin.site.site_title = 'The Campaigns Library'
admin.site.site_header = 'The Campaigns Library'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^categories/$', ResourceCategoryListView.as_view(), name='resource-category-list'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^directory/', include('directory.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^api/v1/', include('api.v1.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
    ),
]

# Make it easier to see a 404 page under debug
if settings.DEBUG:
    from django.views.defaults import page_not_found

    urlpatterns += [
        url(r'^404/$', page_not_found, {'exception': None}),
    ]

# Only enable debug toolbar if it's an installed app
if apps.is_installed('debug_toolbar'):
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Serving static/media under debug
urlpatterns += static(settings.STATIC_URL, never_cache(staticfiles_serve))
urlpatterns += static(settings.MEDIA_URL, never_cache(serve), document_root=settings.MEDIA_ROOT)


def handler500(request, template_name='500.html'):
    """ 500 handler with request context. """
    try:
        template = loader.get_template(template_name)
    except TemplateDoesNotExist:
        return HttpResponseServerError('<h1>Server Error (500)</h1>', content_type='text/html')
    return HttpResponseServerError(template.render({
        'request': request,
    }))

apps/comments/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from resources.models import Resource


class Comment(models.Model):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    body = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return '{user} - {created_at}'.format(user=self.created_by, created_at=self.created_at)


class Report(models.Model):
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reviewed = models.BooleanField(default=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

apps/accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (  # yapf: disable
    AuthenticationForm as BaseAuthenticatonForm, PasswordChangeForm as BasePasswordChangeForm,
    PasswordResetForm as BasePasswordResetForm, SetPasswordForm as BaseSetPasswordForm,
    UserChangeForm as BaseUserChangeForm, UserCreationForm as BaseUserCreationForm
)
from django.utils.safestring import mark_safe

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Field, Layout, Submit

from directory.models import Organisation

from .models import User


class AdminUserCreationForm(BaseUserCreationForm):

    class Meta:
        model = User
        fields = ('email',)


class AdminUserChangeForm(BaseUserChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user = self.request.user
        if user.is_staff and not user.is_superuser:
            # Sometimes is not there if it's set to readonly field in admin.py
            if 'approved_organisations' in self.fields:
                self.fields['approved_organisations'].queryset = user.approved_organisations.all()


class UserRegistrationForm(forms.ModelForm):

    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password = forms.CharField(
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    confirm_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput,
    )
    privacy_agreement = forms.BooleanField(
        required=True,
        label='I agree to The Campaigns Library contacting me about my membership.',
        help_text=mark_safe(
            '''
            Your personal information will be held securely. By submitting information you are
            agreeing to the use of data and cookies in accordance with our
            <a href="/privacy/" target="_blank">privacy policy</a>.
            '''
        )
    )

    class Meta:
        model = User
        fields = (
            'email', 'password', 'confirm_password', 'first_name', 'last_name',
            'chosen_organisations', 'photo', 'phone', 'address'
        )
        labels = {
            'chosen_organisations': 'Groups',
        }
        help_texts = {
            'chosen_organisations':
                """
                Check all of the options that apply to you. If you don't belong to an existing
                group, please select 'Individual Changemaker'.
                """,
        }
        widgets = {
            'address': forms.TextInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['chosen_organisations'].widget = forms.CheckboxSelectMultiple()
        self.fields['chosen_organisations'].required = True

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'email',
            'password',
            'confirm_password',
            'first_name',
            'last_name',
            'chosen_organisations',
            Div(
                Field('photo', css_class="sr__input"),
                Div(css_class='file-mount'),
                css_class='file-group'
            ),
            'phone',
            'address',
            'privacy_agreement',
            ButtonHolder(
                Submit('submit', 'Apply for access', css_class='submit'), css_class='form-actions'
            ),
        )

    def save(self, commit=True):
        password = self.cleaned_data['confirm_password']
        user = super().save(commit=False)
        user.set_password(password)
        if commit:
            user.save()
            self.grant_organisation(user)
            self.save_m2m()
        return user

    def grant_organisation(self, user):

        email_domain = user.get_email_domain()

        if Organisation.objects.filter(email__icontains=email_domain).exists():

            # more than one org can share the same email domain
            # find all organisations that have been selected in the form that also contain the
            # same email domain as the user
            organisations = Organisation.objects.filter(
                email__icontains=email_domain,
                pk__in=self.cleaned_data['chosen_organisations'].values_list("pk", flat=True)
            )

            # if orgs match the query, add the orgs who's email domain matches that of the user
            if organisations.exists():
                org_domain_matches = [
                    org for org in organisations if org.get_email_domain() == email_domain
                ]
                user.approved_organisations.add(*org_domain_matches)
        return user

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(confirm_password)
        return confirm_password


class LoginForm(BaseAuthenticatonForm):

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username', 'password',
            ButtonHolder(
                HTML(
                    """
                    <a href="{% url 'accounts:password-reset' %}">Forgot your password?</a>
                    """
                ),
                Submit('submit', 'Login', css_class='submit'),
                css_class='form-actions'
            ),
            HTML(
                """
                {% if next %}<input type="hidden" name="next" value="{{ next }}">{% endif %}
                """
            )
        )


class PasswordResetForm(BasePasswordResetForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class SetPasswordForm(BaseSetPasswordForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'photo', 'phone', 'address')

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'first_name',
            'last_name',
            'email',
            Div(
                Field('photo', css_class="sr__input"),
                Div(css_class='file-mount'),
                css_class='file-group'
            ),
            'phone',
            'address',
            ButtonHolder(Submit('submit', 'Update', css_class='submit'), css_class='form-actions'),
        )


class PasswordChangeForm(BasePasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Change'))

apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from resources.choices import RESOURCE_WAITING_FOR_APPROVAL

from .forms import UserRegistrationForm, UserUpdateForm
from .models import User


class UserCreateView(CreateView):
    form_class = UserRegistrationForm
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('accounts:registration-thank-you')


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['resources_created'] = user.resources_created.approved().count()
        context['resources_liked'] = user.resources_likes.approved().count()
        context['resources_tried'] = user.resources_tried.approved().count()
        context['resources_waiting_for_approval'] = user.resources_created.filter(
            status=RESOURCE_WAITING_FOR_APPROVAL
        )
        return context

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('accounts:user-detail')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'The user profile was successfully updated.')
        return super().form_valid(form)

templates/accounts/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block main_content %}
  <div class="form-holder">
    {% crispy form %}

    <div class="form-holder__footer">
      <p>Don't have an account? <a href="{% url 'accounts:registration' %}">Click here</a> to become a member of The Campaigns Library.</p>
    </div>
  </div>
{% endblock main_content %}

templates/accounts/logout.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block main_content %}
  <div class="form-feedback">
    <h4>You are now logged out. See you again soon.</h4>

    <p>Want to log back in? <a href="{% url 'accounts:login' %}">Click here</a></p>
  </div>
{% endblock main_content %}

templates/accounts/password_change.html
{% extends "base.html" %}

{% load crispy_forms_tags staticfiles %}


{% block main_content %}
  <div class="form-holder">
    <h2 class="form-title">Change Password</h2>
    {% crispy form %}
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/forms.js' %}"></script>
{% endblock extra_scripts %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}


{% block main_content %}
  <div class="form-feedback">
    <h4>Your password has been set</h4>

    <p>To log in <a href="{% url 'accounts:login' %}">click here</a></p>
  </div>
{% endblock main_content %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block main_content %}
  {% if validlink %}
    <div class="form-holder">
      <form method="post">
        {% crispy form %}

        <div class="form-actions">
          <input type="submit" value="Change my password" class="btn"/>
        </div>
      </form>
    </div>
  {% else %}
    <div class="form-feedback">
      <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset <a href="{% url 'accounts:password-reset' %}">here</a></p>
    </div>
  {% endif %}
{% endblock main_content %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}


{% block main_content %}
  <div class="form-feedback">
    <h4>Password reset sent.</h4>
    <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>
{% endblock main_content %}

templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block main_content %}
  <div class="form-holder">
    <h2 class="form-title">Reset your password</h2>
    <form method="POST">
      {% crispy form %}
      <div class="form-actions">
        <input type="submit" value="Submit" class="btn submit">
      </div>
    </form>
  </div>
{% endblock main_content %}

templates/accounts/registration.html
{% extends "base.html" %}

{% load crispy_forms_tags staticfiles %}

{% block main_content %}
  <div class="form-holder">
    <h2 class="form-title">Become a member</h2>
    {% crispy form %}
    <hr />
    <h2>Membership Policy</h2>
    <p>Members are the backbone of our community.</p>
    <p>
      As a member, you can provide the extra insights that bring our resources alive,
      and help our knowledge base grow by uploading your own resources about innovation
      and best practice in campaigning and organising.
    </p>
    <p>
      Anyone can become a member of The Campaigns Library. You just have to register,
      by filling out the form above. Once your registration is received, the Librarian
      will have a look and make sure your account is set up correctly. Then you’ll be up and running!
    </p>
    <p>Once you are a member, you’ll be able to log in and:</p>
    <ul>
      <li>Let the community know which resources have worked best for you;</li>
      <li>Leave feedback and tips for others, and join in discussions via comments;</li>
      <li>Connect with other members;</li>
      <li>Receive updates, news and tips from the Librarian; and</li>
      <li>Upload your own resources, helping our Workspace grow.</li>
    </ul>
    <p>
      The Campaigns Library is also a resource in and of itself - our own platform and information
      architecture system is fully open source. <strong>Your organisation can use the Library as its
      own resource management tool, and maintain either a public or private collection.</strong>
      Note that there are <a href="/terms/">Terms and Conditions of Use</a> applicable.
    </p>
    <p>
      If you already belong to an Organisation with a collection please indicate this when you register,
      and the Librarian will confirm your access to the relevant Organisations.
    </p>
    <p>
      If your organisation would like its own private collection, or to upload resources to the public Library,
      get in touch with the Librarian at <a href="mailto:librarian@the-open.org">librarian@the-open.org</a>
    </p>
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/forms.js' %}"></script>
{% endblock extra_scripts %}

templates/accounts/user_detail.html
{% extends 'base.html' %}

{% load thumbnail staticfiles %}


{% block extra_head %}
  {% if organisation.colour %}
    <style>
      body {
        --page-group: {{ organisation.colour }};
      }
    </style>
  {% endif %}
{% endblock extra_head %}

{% block main_content %}
  <div class="profile-summary">
    <div class="profile-summary__image">
      {% thumbnail user.photo '1200' as thumb %}
        <div class="profile-image__full" style="background: url({{ thumb.url }}) center center/cover no-repeat">
        </div>
      {% endthumbnail %}
      <div class="profile-image__details">
        <h3 class="profile-image__title">{{ user.get_full_name }}</h3>

        {% for organisation in user.approved_organisations.all %}
          <div class="profile-summary__group">
            {% thumbnail organisation.logo '250' as thumb %}
              <div class="group-logo" style="background: url({{ thumb.url }}) center center/contain no-repeat"></div>
            {% endthumbnail %}
            <span><a href="{% url 'directory:organisation-detail' organisation.slug %}">{{ organisation.title }}</a></span>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="profile-summary__details">
      {% if request.user == user %}
        <div class="profile-buttons">
          <a href="{% url "accounts:user-update" %}">
            <svg class="icon">
              <use xlink:href="#profile"></use>
            </svg>Update Profile
          </a>
          <a href="{% url "accounts:password-change" %}">
            <svg class="icon">
              <use xlink:href="#private"></use>
            </svg>Change password
          </a>
        </div>
      {% endif %}
      <div class="profile-summary__identity">
        <h1 class="profile-summary__title">
          {{ user.get_full_name }}
        </h1>

        {% for organisation in user.approved_organisations.all %}
          <div class="profile-summary__group">
            {% thumbnail organisation.logo '250' as thumb %}
              <div class="group-logo" style="background: url({{ thumb.url }}) center center/contain no-repeat"></div>
            {% endthumbnail %}
            <span><a href="{% url 'directory:organisation-detail' organisation.slug %}">{{ organisation.title }}</a></span>
          </div>
        {% endfor %}
      </div>
      <div class="profile-details">
        <div class="icon-list">
          {% if user.phone %}
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#phone"></use>
              </svg>
              <div class="contact-detail__value">
                {{ user.phone }}
              </div>
            </div>
          {% endif %}
          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#email"></use>
            </svg>
            <div class="contact-detail__value">
              <a href="#">{{ user.email }}</a>
            </div>
          </div>
          {% if user.address %}
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#map"></use>
              </svg>
              <div class="contact-detail__value">
                {{ user.address|linebreaks }}
              </div>
            </div>
          {% endif %}
        </div>
        <div class="icon-list">

          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#create"></use>
            </svg>
            <div class="profile-detail__value">
              {{ resources_created }} resource{{ resources_created|pluralize }} added
            </div>
          </div>

          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#comment"></use>
            </svg>
            <div class="profile-detail__value">
              {% with total_comments=user.comment_set.count %}
                {{ total_comments }} comment{{ total_comments|pluralize }} posted
              {% endwith %}
            </div>
          </div>

          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#liked"></use>
            </svg>
            <div class="profile-detail__value">
              {{ resources_liked }} resource{{ resources_liked|pluralize }} liked
            </div>
          </div>

          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#tried"></use>
            </svg>
            <div class="profile-detail__value">
              {{ resources_liked }} resource{{ resources_liked|pluralize }} tried
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if user.get_latest_resource or user.get_most_liked_resource or user.get_most_tried_resource %}
    <div class="resources featured-resources">
      <div class="resources-grid">
        {% include "includes/resource.html" with resource=user.get_latest_resource resource_category="latest" %}
        {% include "includes/resource.html" with resource=user.get_most_liked_resource resource_category="Most Liked" %}
        {% include "includes/resource.html" with resource=user.get_most_tried_resource resource_category="Most Tried" %}
      </div>
    </div>
  {% endif %}

  <div id="react-app" data-user="{{ user.pk }}">
    {% csrf_token %}
  </div>

  {% if resources_waiting_for_approval %}
    <div class="awaiting-approval">
      <h3>You have <strong>{{ resources_waiting_for_approval.count }} resource{{ resources_waiting_for_approval|pluralize }}</strong> waiting for approval </h3>
      <div class="resources-grid">
        {% for resource in resources_waiting_for_approval %}
          {% include "includes/resource.html" %}
        {% endfor %}
      </div>
    </div>
  {% endif %}

{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/main.js' %}"></script>
{% endblock extra_scripts %}

templates/accounts/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags staticfiles %}


{% block main_content %}
  <div class="form-holder">
    <h2 class="form-title">Update Profile</h2>
    {% crispy form %}
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/forms.js' %}"></script>
{% endblock extra_scripts %}