apps/directory/urls.py
from django.conf.urls import url

from .views import OrganisationDetailView, OrganisationListView, OrganisationUserView

app_name = 'directory'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', OrganisationDetailView.as_view(), name='organisation-detail'),
    url(r'^$', OrganisationListView.as_view(), name='organisation-list'),
    url(r'^people/(?P<pk>\d+)/$', OrganisationUserView.as_view(), name='organisation-user'),
]

apps/resources/urls.py
from django.conf.urls import url

from comments.views import CommentUpdateView, ReportCommentView
from pages.views import PageDetailView

from .views import (
    ResourceCategoryDetailView, ResourceCreateView, ResourceDetailView, ResourceUpdateView,
    admin_categorise_resources_view
)

app_name = 'resources'
urlpatterns = [
    url(
        r'categorise-resources/$',
        admin_categorise_resources_view,
        name='admin-categorise-resources'
    ),
    url(r'^add/$', ResourceCreateView.as_view(), name='resource-create'),
    url(r'^thank-you/$', PageDetailView.as_view(), name='resource-thank-you'),
    url(
        r'^category/(?P<slug>[\w-]+)/$',
        ResourceCategoryDetailView.as_view(),
        name='resource-category-detail'
    ),
    url(r'^(?P<slug>[\w-]+)/$', ResourceDetailView.as_view(), name='resource-detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', ResourceUpdateView.as_view(), name='resource-update'),
    url(
        r'^(?P<slug>[\w-]+)/(?P<id>[0-9]+)/report-comment/$',
        ReportCommentView.as_view(),
        name='resource-report-comment',
    ),
    url(
        r'^(?P<slug>[\w-]+)/(?P<id>[0-9]+)/update-comment/$',
        CommentUpdateView.as_view(),
        name='resource-update-comment',
    ),
]

commonslibrary/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve as staticfiles_serve
from django.http import HttpResponseServerError
from django.template import TemplateDoesNotExist, loader
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.views.static import serve

from core.views import HomeView, SearchView
from resources.views import ResourceCategoryListView

admin.site.site_title = 'The Campaigns Library'
admin.site.site_header = 'The Campaigns Library'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^categories/$', ResourceCategoryListView.as_view(), name='resource-category-list'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^directory/', include('directory.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^api/v1/', include('api.v1.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),
    ),
]

# Make it easier to see a 404 page under debug
if settings.DEBUG:
    from django.views.defaults import page_not_found

    urlpatterns += [
        url(r'^404/$', page_not_found, {'exception': None}),
    ]

# Only enable debug toolbar if it's an installed app
if apps.is_installed('debug_toolbar'):
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Serving static/media under debug
urlpatterns += static(settings.STATIC_URL, never_cache(staticfiles_serve))
urlpatterns += static(settings.MEDIA_URL, never_cache(serve), document_root=settings.MEDIA_ROOT)


def handler500(request, template_name='500.html'):
    """ 500 handler with request context. """
    try:
        template = loader.get_template(template_name)
    except TemplateDoesNotExist:
        return HttpResponseServerError('<h1>Server Error (500)</h1>', content_type='text/html')
    return HttpResponseServerError(template.render({
        'request': request,
    }))

apps/comments/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from resources.models import Resource


class Comment(models.Model):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    body = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return '{user} - {created_at}'.format(user=self.created_by, created_at=self.created_at)


class Report(models.Model):
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reviewed = models.BooleanField(default=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

templates/resources/resource_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags staticfiles thumbnail %}


{% block header_content %}
  {% include 'includes/header.html' with action_buttons='true' %}
  {% include "includes/messages.html" %}
{% endblock header_content %}

{% block main_content %}
  {% csrf_token %}
  <main class="resource-holder" data-resource="{{ resource.id }}">
    <aside class="resource-sidebar" id="resource_sidebar">
      {% include "includes/resource_actions.html" %}
      <div class="resource-meta">
        <div class="icon-list">
          {% if resource.privacy.exists %}
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#private"></use>
              </svg>
              <div class="icon-list__content">
                <p>Private resource for
                {% for org in resource.privacy.all %}
                  {{ org.title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
              </div>
            </div>
          {% endif %}
          <div class="icon-list__row name-row">
            <svg class="icon">
              <use xlink:href="#directory"></use>
            </svg>
            <div class="icon-list__content">
              {% thumbnail resource.created_by.photo '500' as thumb %}
                <div class="profile-image small" style="background: url({{ thumb.url }}) center center/cover no-repeat"></div>
              {% endthumbnail %}
              <p class="profile-name"><a href="{% url 'directory:organisation-user' resource.created_by.pk %}">{{ resource.created_by.get_full_name }}</a></p>
            </div>
          </div>
          <div class="icon-list__row group-row">
            {% thumbnail resource.organisation.logo '250' as thumb %}
              <div class="icon profile-image small" style="background: url({{ thumb.url }}) center center/contain no-repeat"></div>
            {% endthumbnail %}
            <div class="icon-list__content">
              <p class="profile-group"><a href="{% url 'directory:organisation-detail'  resource.organisation.slug %}">{{ resource.organisation }}</a></p>
            </div>
          </div>
          <div class="icon-list__row">
            <svg class="icon">
              <use xlink:href="#date"></use>
            </svg>
            <div class="icon-list__content">
              <p>{{ resource.created_at|date:'j F Y H:i' }}</p>
            </div>
          </div>
          {% if resource.tags.exists %}
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#tag"></use>
              </svg>
              <div class="icon-list__content">
                <div class="tag-list">
                  {% for tag in resource.tags.all %}
                    <a href="{% url 'search' %}?tags={{ tag.id }}" class="tag">{{ tag }}</a>
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}
          <div class="icon-list__row" id="comment_stats">
            <svg class="icon">
              <use xlink:href="#comment"></use>
            </svg>
            <div class="icon-list__content">
              {% with total_comments=resource.comment_set.count %}
              {{ total_comments }} comment{{ total_comments|pluralize }}
              {% endwith %}
              {{ people_commented }} People
            </div>
          </div>

          {% if editable %}
            <div class="icon-list__row edit-resource">
              <svg class="icon">
                <use xlink:href="#create"></use>
              </svg>
              <div class="icon-list__content">
                <a href="{% url 'resources:resource-update' object.slug %}">Edit this resource</a>
              </div>
            </div>
          {% endif %}

        </div>
      </div>
    </aside>

    <article class="resource-detail">
      <header class="resource-header">
        {% thumbnail resource.image '1200' as thumb %}
          <div class="resource-header__background" style="background: url({{ thumb.url }}) center center/cover no-repeat"></div>
        {% empty %}
          <div class="resource-header__background"></div>
        {% endthumbnail %}
        <div class="resource-title">
          <h1>
            <span>{{ resource.title }}</span>
          </h1>
        </div>
        <div class="resource-subtitle">
          <h3>
            <span>{{ resource.abstract }}</span>
          </h3>
        </div>
      </header>
      <div class="resource-content">
        <div class="resource-detail__stats hide-desktop">
          <div class="icon-list">
            {% if resource.privacy.exists %}
              <div class="icon-list__row">
                <svg class="icon">
                  <use xlink:href="#private"></use>
                </svg>
                <div class="icon-list__content">
                  <p>Private resource for
                  {% for org in resource.privacy.all %}
                    {{ org.title }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                  </p>
                </div>
              </div>
            {% endif %}
            <div class="icon-list__row group-row">
              {% thumbnail resource.organisation.logo '250' as thumb %}
                <div class="icon profile-image small" style="background: url({{ thumb.url }}) center center/contain no-repeat"></div>
              {% endthumbnail %}
              <div class="icon-list__content">
                <p class="profile-name"><a href="{% url 'directory:organisation-user' resource.created_by.pk %}">{{ resource.created_by.get_full_name }}</a></p>
                <p class="profile-group"><a href="{% url 'directory:organisation-detail'  resource.organisation.slug %}">{{ resource.organisation }}</a></p>
              </div>
            </div>
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#date"></use>
              </svg>
              <div class="icon-list__content">
                <p>{{ resource.created_at|date:'j F Y H:i' }}</p>
              </div>
            </div>
            {% if editable %}
              <div class="icon-list__row edit-resource">
                <svg class="icon">
                  <use xlink:href="#create"></use>
                </svg>
                <div class="icon-list__content">
                  <a href="{% url 'resources:resource-update' object.slug %}">Edit this resource</a>
                </div>
              </div>
            {% endif %}
          </div>
        </div>

        <div class="resource-content__body">
          {{ resource.content|safe }}
        </div>
        {% if resource.tags.exists %}
          <footer class="resource-detail__stats hide-desktop">
            <div class="icon-list__row">
              <svg class="icon">
                <use xlink:href="#tag"></use>
              </svg>
              <div class="icon-list__content">
                <div class="tag-list">
                  {% for tag in resource.tags.all %}
                    <a href="{% url 'search' %}?tags={{ tag.id }}" class="tag">{{ tag }}</a>
                  {% endfor %}
                </div>
              </div>
            </div>
          </footer>
        {% endif %}

      </div>

      {% if not waiting_for_approval %}
        <div class="comments">
          <div class="comments-title">
            <svg class="icon">
              <use xlink:href="#comment"></use>
            </svg>
            <h4>Comments</h4>
          </div>
          {% for comment in resource.comment_set.all %}
            {% include "includes/comments.html" with comment=comment %}
          {% empty %}
            <div class="comment">
              <div class="comment-content">
                  <p class="no-comments">There are currently no comments.</p>
                </div>
              </div>
          {% endfor %}

          {% if user.is_authenticated %}
            <div class="comments-form form-holder">
              <div class="comment-profile">
                {% thumbnail user.photo "x50" as thumb %}
                  <div class="group-logo" style="background: url({{ thumb.url }}) center center/contain no-repeat"></div>
                {% endthumbnail %}
                <span>{{ user.get_full_name }}</span>
              </div>
              {% crispy form %}
            </div>
          {% endif %}
        </div>
      {% endif %}

      {% if not waiting_for_approval %}
        {% if related_resources %}
          <div class="related-resources">
            <h4 class="related-resources__title">
              <svg class="icon">
                <use xlink:href="#network"></use>
              </svg>
              <span>Related resources</span>
            </h4>
            <div class="related-resources__grid">
              {% for resource in related_resources %}
                {% include "includes/resource.html" %}
              {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endif %}

  </main>


{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/resource.js' %}"></script>
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "NewsArticle",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "{{ resource.get_absolute_url }}"
      },
      "headline": "{{ resource.title }}",
      "image": [
        "{% thumbnail resource.image '1200' as thumb %}{{ thumb.url }}{% endthumbnail %}"
       ],
      "datePublished": "{{ resource.created_at }}",
      "author": {
        "@type": "Person",
        "name": "{{ resource.created_by.get_full_name }}"
      },
       "publisher": {
        "@type": "Organization",
        "name": "{{ resource.organisation }}",
        "logo": {
          "@type": "ImageObject",
          "url": "{% thumbnail resource.organisation.logo '250' as thumb %}{{ thumb.url }}{% endthumbnail %}"
        }
      },
      "description": "{{ resource.abstract }}"
    }
  </script>

{% endblock extra_scripts %}

templates/resources/resource_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags staticfiles %}


{% block main_content %}
  <div class="form-holder">
    <p>
      We hope all changemakers consider publicly sharing the resources they find most useful!
      Together, we can grow our collective knowledge and skill up our community. You can submit your resource here.
    </p>
    <p>
      When you submit a resource, it goes to the Librarian for approval. If there is a problem with your resource,
      the Librarian will reach out to you directly. If everything is in order, your resource will be published.
    </p>
    <p>
      When your resource is published on The Campaigns Library, it still belongs to you. You can edit its content and privacy
      settings at any time through the site, and remove it completely by emailing the librarian at
      <a href="mailto:librarian@the-open.net">librarian@the-open.net</a>
    </p>
    <p>
      The Campaigns Library will honour your privacy selection, whether your resource is publicly available or
      can be seen only by members of your group or organisation. The Library is not liable for any copying or
      further distribution that may occur once your resource has been shared on the site.
    </p>

    {% crispy form %}
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/forms.js' %}"></script>
{% endblock extra_scripts %}

templates/resources/resource_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags staticfiles %}


{% block main_content %}
  <div class="form-holder">
    <h2>Update resource</h2>
    {% crispy form %}
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/forms.js' %}"></script>
{% endblock extra_scripts %}

templates/resources/resourcecategory_detail.html
{% extends 'base.html' %}

{% load thumbnail staticfiles %}


{% block main_content %}
  {% thumbnail resourcecategory.image '500' as category_image %}
    <div class="background" style="background: url({{ category_image.url }}) center center/cover no-repeat">
      <div class="backgroundContent">
        <div class="backButtonHolder">
          <a href="{% url 'resource-category-list' %}" class="backButton button">
            <span>All Categories</span>
          </a>
        </div>
        <div class="resource-title">
          <h1>
            <span>{{ resourcecategory.title }}</span>
          </h1>
        </div>
        <div class="resource-subtitle">
          <h3>
            <span>{{ resourcecategory.description }}</span>
          </h3>
        </div>
      </div>
    </div>
  {% endthumbnail %}

  {% if featured_resources.exists %}
    <div class="featured-resources detail-page__featured-resources">
      <h3> Featured Resources</h3>
      <div class="resources-grid">
        {% for resource in featured_resources %}
          {% include 'includes/resource.html' %}
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <div id="react-app" data-hidesearch="true" data-category="{{ resourcecategory.pk }}">
    {% csrf_token %}
  </div>

{% endblock %}


{% block extra_scripts %}
  <script src="{% static 'dist/js/main.js' %}"></script>
{% endblock extra_scripts %}

templates/resources/resourcecategory_list.html
{% extends "base.html" %}

{% load thumbnail staticfiles resource_count %}


{% block main_content %}
  <div class="explore">
    <div class="categories-grid">
      <div class="explore-tags">
        <div class ="intro">
          <h1>Categories</h1>
          <h3>Browse the collection. Click on a category to find out more and see featured resources.</h3>
        </div>
        <div class="category-grid">
          {% for category in resourcecategory_list %}
            {% thumbnail category.image '500' as category_image %}
              <div class="category-grid__item" style="background: url({{ category_image.url }}) center center/cover no-repeat">
                <div class="category-grid__item-detail">
                  <a href="#" class="category_toggle" data-target="{{ category.pk }}">
                    <h3>{{ category.title }}</h3>
                    {% resource_count category request.user as resource_count %}
                    <p>{{ resource_count }} resource{{ resource_count|pluralize }}</p>
                  </a>
                </div>
              </div>
            {% endthumbnail %}
            <div class="resources-holder hidden" data-category="{{ category.pk }}">
              <div class="resource-description">
                <div class="close-button-holder">
                  <svg class="icon close-resource">
                    <use xlink:href="#remove"></use>
                  </svg>
                </div> 
                <h1>{{ category.title }}</h1>
                <p>{{ category.description }}</p>
                <div class="more-button-holder">
                  <a href="{{ category.get_absolute_url }}" class="more-button button">See all resources</a>
                </div>
              </div>
              <div class="featured-resources">
                <h5> Featured resources </h5>
                <div class="featured-resources__holder">
                  {% for featured_resource in category.get_approved_featured_resources|slice:':2' %}
                    {% include 'includes/resource.html' with resource=featured_resource %}
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock main_content %}

{% block extra_scripts %}
  <script src="{% static 'dist/js/categories.js' %}"></script>
{% endblock extra_scripts %}